options:
  merge-default-rules: false
  formatter: stylish
files:
  include: '_resources/sass/**/*.s+(a|c)ss'
  ignore:
    - '_resources/sass/vendor/**/*.*'
    - '_resources/sass/themes/**/*.*'
    - '_resources/sass/base/_normalize.scss'
    # Sass, @keyframes, and sass-lint don't mix
    - '_resources/sass/_animations.sass'
rules:
  attribute-quotes:
    - 2
    - include: true
  bem-depth: 0
  border-zero:
    - 2
    - convention: '0'
  brace-style: 0
  # class-name-format:
  #   - 2
  #   - allow-leading-underscore: true
  #   - convention: strictbem
  clean-import-paths:
    - leading-underscore: false
    - filename-extension: false
  empty-args: 0
  empty-line-between-blocks: 1
  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: true
    - convention: 'hyphenatedlowercase'
    - convention-explanation: 'Your awesome!'
  hex-length:
    - 2
    - style: long
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 0
    # - size: 'tab'
    - FIXME
  leading-zero:
    - 2
    - include: true
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
    - convention: 'hyphenatedlowercase'
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 1
  # no-css-comments: 2 FIXME
  no-debug: 2
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-qualifying-elements:
    - allow-element-with-attribute: true
    - allow-element-with-class: false
    - allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-protocols: 2
  # no-vendor-prefixes: FIXME
  #   - ignore-non-standard: false
  #   -
  #   - excluded-properties:
  #     - '-webkit-scrollbar-track'
  no-warn: 2
  one-declaration-per-line: 2
  property-sort-order:
    - order: 'alphabetical'
    - ignore-custom-properties: true
  quotes:
    - style: single
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-between-parens:
    - 2
    - include: false
  url-quotes: 2
  variable-name-format:
    - convention: strictbem
    - allow-leading-underscore: false
    - convention-explanation: 'Awesome!'
  zero-unit:
    - 2
    - include: false
